config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  #admin
  devise_for :admins, controllers: {
    sessions: 'admin/devise/sessions',
    passwords: "admin/devise/passwords",
    registrations: "admin/devise/registrations",
  }




  #customer
  devise_for :customers, controllers: {
    sessions: 'customer/devise/sessions',
    passwords: "customer/devise/passwords",
    registrations: "customer/devise/registrations",
  }




  #customer
  root 'customer/homes#top'
  get 'homes/about' => 'customer/homes#about', as: 'about'
  get 'homes/party' => 'customer/homes#party', as: 'party'
  get 'homes/wedding' => 'customer/homes#wedding', as: 'wedding'
  get 'homes/hygiene' => 'customer/homes#hygiene', as: 'hygiene'


  scope module: :customer do
    resources :reservations, only: [:new, :index, :create, :destroy]
    resources :topics, only: [:index, :show] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end




  #admin
  get 'admins/home/top' => 'admin/homes#top', as: 'admin_top'


  namespace :admin do
    resources :topics, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    resources :inquiries, only: [:index, :show]
    resources :reservations, only: [:index, :show]
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

    self.abstract_class = true

end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :topic
    belongs_to :customer

end

app/models/customer.rb
class Customer < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable


    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :reservations, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord


    belongs_to :topic
    belongs_to :customer


    validates_uniqueness_of :topic_id, scope: :customer_id


end

app/models/inquirie.rb
class Inquirie < ApplicationRecord

    belongs_to :admin

end

app/models/reservation.rb
class Reservation < ApplicationRecord

    belongs_to :customer
    belongs_to :admin


    validates :first_name, presence: true
    validates :last_name,  presence: true
    validates :first_name_kana, presence: true
    validates :last_name_kana,  presence: true
    validates :tel, presence: true
    validates :email, presence: true
    validates :people, presence: true

end

app/models/topic.rb
class Topic < ApplicationRecord


    belongs_to :admin


    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy


    attachment :image, destroy: false


    validates :title, presence: true, length: {maximum: 30, minimum: 2}
    validates :body, presence: true
    validates :image, presence: true


    def favorited_by?(customer)
      favorites.where(customer_id: customer.id).exists?
    end


    def previous
      Topic.where("id < ?", self.id).order("id DESC").first
    end


    def next
      Topic.where("id > ?", self.id).order("id ASC").first
    end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController


    before_action :authenticate_admin!


    def top
      range = Date.today.beginning_of_day..Date.today.end_of_day
    end


end

app/controllers/admin/inquiries_controller.rb
class Admin::InquiriesController < ApplicationController
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController


    before_action :authenticate_admin!


    def new
      @topic = Topic.new
    end


    def index
      @topics = Topic.all.order(created_at: :desc)
      @topic = Topic.new
    end


    def show
      @topic = Topic.find(params[:id])
    end


    def edit
      @topic = Topic.find(params[:id])
    end


    def update
      @topic = Topic.find(params[:id])
      if @topic.update(topic_params)
        flash[:notice] = "TOPICが変更されました。"
        redirect_to admin_topic_path(@topic.id)
      else
        render "edit"
      end
    end


    def create
      @topic = Topic.new(topic_params)
      @topic.admin_id = current_admin.id
      @topics = Topic.all
      if @topic.save!
        flash[:notice] = "TOPICが保存されました。"
        redirect_to admin_topic_path(@topic)
      else
        flash[:alert] = "再度入力してください。"
        render 'index'
      end
    end


    def destroy
      @topic = Topic.find(params[:id])
      @topic.destroy
      redirect_to admin_topics_path
    end





    private

        def topic_params
          params.require(:topic).permit(:title, :body, :image)
        end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
      case resource
      when Admin
        admin_top_path
      when Customer
        root_path
      end
    end


    def after_sign_up_path_for(resource)
      case resource
      when Admin
        admin_top_path
      when Customer
        root_path
      end
    end


    def after_sign_out_path_for(resource)
      if resource == :admin
        new_admin_session_path
      else
        new_customer_session_path
      end
    end






    private

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:is_enabled, :name, :email, :password])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
      end


end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController


    def create
      topic = Topic.find(params[:topic_id])
      comment = current_customer.comments.new(comment_params)
      comment.topic_id = topic.id
      comment.save
      redirect_back(fallback_location: root_path)
    end


    def destroy
      @comment = Comment.find(params[:topic_id])
      @comment.destroy
      redirect_back(fallback_location: root_path)
    end





    private

      def comment_params
        params.require(:comment).permit(:comment)
      end


end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController


    def create
  	  topic = Topic.find(params[:topic_id])
      favorite = current_customer.favorites.new(topic_id: topic.id)
      favorite.save
      redirect_to topic_path(topic)
    end


    def destroy
  	  topic = Topic.find(params[:topic_id])
      favorite = current_customer.favorites.find_by(topic_id: topic.id)
      favorite.destroy
      redirect_to topic_path(topic)
    end


end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController


    def top
      @topics = Topic.all.order(created_at: :desc)
    end


end

app/controllers/customer/inquiries_controller.rb
class Customer::InquiriesController < ApplicationController
end

app/controllers/customer/reservations_controller.rb
class Customer::ReservationsController < ApplicationController
end

app/controllers/customer/topics_controller.rb
class Customer::TopicsController < ApplicationController


    def index
      @topic = Topic.new
      @topics = Topic.all.order(created_at: :desc).page(params[:page])
    end


    def show
      @topics = Topic.find(params[:id])
      @comment = Comment.new
  	  @comments = @topics.comments
      @topic_new = Topic.new
    end


end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/comments_helper.rb
module Customer::CommentsHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/inquiries_helper.rb
module Customer::InquiriesHelper
end

app/helpers/customer/reservations_helper.rb
module Customer::ReservationsHelper
end

app/helpers/customer/topics_helper.rb
module Customer::TopicsHelper
end

app/views/customer/homes/about.html.erb
<h3>Bell Foret</h3>


料理は愛から始まる芸術です。<br>
人を愛し、食材を愛すること。<br>
愛情は料理に現れます。<br>
私たちシェフが料理をするとき、まず想うこと。<br>
それは出来上がった料理をお客様が心より美味しそうに嬉しそうに召し上がってくださる姿です。<br>
絵画や映画など人の心を動かす全ての芸術がそうであるように、料理もまた、創造するプロセスに厳しさを伴うもの。<br>
時には、不安という壁に閉ざされて、身動きできなくなることもあります。<br>
しかし、お客様のその喜びで輝くような笑顔によって支えられ、料理がもたらす愛のメッセージによって励まされ、<br>
私たちは常に前に進むことができるのです。<br>
今日も私たちのつくる一皿が、皆様に幸せなひとときを贈ることを願って。<br>
ボナペティ！


La cuisine est un acte d’Amour, parce que nous l'expérimentons d'abord à l'approbation de ceux susceptibles de la découvrir.<br>
C'est pour ça, que la musique comme la peinture,<br>
comme tout ce qui est beau, est un Art exigeant qui suppose de notre côté,<br>
une régularité, une inquiétude qui n'est réconforté que par le massage d'Amour qu'elle apporte.<br>
Si la musique nous transporte dans un message d'Amour, si la peinture, nous réunit dans une admiration universelle, il faut que la cuisine entraîne chez nous une attitude semblable.<br>
Bon appétit!

app/views/customer/homes/hygiene.html.erb
<h3>TOPICSS</h3>


<h3>新型コロナウイルス等の感染予防対策について</h3>

いつも BelleForet をご利用いただき、誠にありがとうございます。<br>

BelleForet では、お客様ならびにスタッフの健康と安全確保を考慮し、新型コロナウイルス等の感染予防のため、以下対策を実施しております。<br>

また、新型コロナウイルス等の感染予防、及び拡散防止のため、短縮時間での営業とさせていただきます。


<h3>新型コロナウイルス感染予防のための対策</h3>

⦿厚生労働省の対応指針（ガイドライン）に基づき、スタッフの手洗い、うがい、アルコール消毒を徹底しております。
　　※アルコール消毒は、CDC（米国疾病予防管理センター）が推奨する基準を満たすアルコール製剤「JAMES MARTIN」を使用しています。<br>

⦿店内にお客様用の手指消毒液を設置しております。<br>

⦿レストランではご来店のお客様には検温にご協力をいただいております。<br>

⦿スタッフは出勤時の体温測定を実施し、発熱や体調不良がうかがえるスタッフの出勤停止を行っております。<br>

⦿スタッフの発熱など症状が確認できる場合は自宅待機のうえ、行政に相談し指示を受けるよう周知徹底しております。<br>


今後も、上記対策による感染拡大の予防策を徹底するとともに、常に状況に応じた適切な対応を行い、お客様ならびにスタッフ、またそのご家族の安心と安全を最優先した対応に努めてまいります。<br>

お客様にはご不便をおかけいたしますが、何卒ご理解のほどよろしくお願い申し上げます。

app/views/customer/homes/party.html.erb
<h3>PARTY</h3>


<h3>フランスの古城を思わせる優雅な個室</h3>


シャトーレストランの最上階に位置する個室。<br>
大切なお客様のおもてなし、ご家族やご友人との記念日のお祝いなど、様々なシーンにご利用いただけます。<br>
ガストロノミー “ Bell Foret ”のお食事を落ち着いた空間でお楽しみください。


<h3>ご予約は会員登録が必要になります。</h3>

app/views/customer/homes/top.html.erb
<div class="container">
    <div class="row">


        <div class="row">
            <div class="top_image">

                <%= image_tag asset_path("photo1.jpg") %>

                <div>
                    <%= image_tag asset_path("photo2.jpg"), class: "slick" %>
                    <%= image_tag asset_path("photo3.jpg"), class: "slick" %>
                </div>

                <%= image_tag asset_path("photo4.jpg") %>

                <div>
                    <%= image_tag asset_path("photo5.jpg"), class: "slick" %>
                    <%= image_tag asset_path("photo6.jpg"), class: "slick"  %>
                </div>

                <%= image_tag asset_path("photo7.jpg") %>

            </div>
        </div>


        <div class="row">
            <%= link_to "新型コロナウイルス等の感染予防対策について", hygiene_path %>
        </div>


        <div class="title_customer_top">TOPICS</div>


        <div class="row">
            <% @topics.first(6).each do |topic| %>
                <%= link_to topic_path(topic.id) do %>
                    <%= topic.updated_at.strftime("%Y-%m-%d %H:%M") %><br>
                    <%= attachment_image_tag topic, :image, format: 'jpeg',  fallback: "no_image.jpg"%><br>
                    <%= topic.title %>
                <% end %>
            <% end %>
        </div>


        <div class="row">
            <%= link_to "READ MORE", topics_path %>
        </div>


    </div>
</div>

app/views/customer/homes/wedding.html.erb
Belle Foret Wedding


<h3>誰もが憧れる　美食の殿堂でウエディング</h3>

ここは、世界中の人々が一度は訪れてみたいと憧れる美食の殿堂。<br>
高貴さとカジュアルモダン、その両方を同時に漂わせるラベンダーカラーの1階、<br>
シャンパンゴールドとブラックの調和が華やかな気品を醸し出す２階ガストロノミー、<br>
異なるダイニングルームでウエディングパーティを叶えることができる。<br>
また、最上階にはクラシカルな雰囲気が漂う3つの部屋があり、ブライズルーム・親族控室・挙式スペースが完備されているのも魅力。<br>
まるで、フランス貴族の館を思わせる気品あるインテリアや設えで、大切なゲストの皆様と、華やかで優雅な一日をお過ごしください。


<h3>世紀のシェフがプロデュースする フレンチ料理&スイーツで結婚式</h3>

世紀のシェフがプロデュースするフレンチ料理&スイーツで結婚式<br>
優れた料理人は、その人生の中で完結されたお皿を生み出す。<br>
だが誰しもが、作品とも呼べる料理を数多く持てる訳ではない。<br>
その奇跡に出会える場所で大切な一日を。


<h3>PHOTO GALLERY</h3>
<h4>フォトギャラリー</h4>


詳細・お問い合わせ<br>
お二人の理想のウェディングをサポートします。 まずはお問い合わせください。


<h3>ご予約は会員登録が必要になります。</h3>

app/views/customer/reservations/new.html.erb
<div class="container">
    <div class="row">





    </div>
</div>

app/views/customer/topics/index.html.erb
<div class="container">
    <div class="row">


        <div class="title_topics">TOPICS</div>

        <% @topics.each do |topic| %>
            <%= link_to topic_path(topic.id) do %>
                <%= attachment_image_tag topic, :image, format: 'jpeg', size: "300x300",  fallback: "no_image.jpg"%><br>
                <%= topic.updated_at.strftime("%Y-%m-%d %H:%M") %><br>
                <%= topic.title %>
            <% end %>
        <% end %>


        <div class="paginate">
            <%= paginate @topics %>
        </div>


    </div>
</div>

app/views/customer/topics/show.html.erb
<div class="container">
    <div class="row">


        <div class="title_topics">TOPIC</div>


        <div class="row">

            <div class="update">
                <%= @topic.updated_at.strftime("%Y-%m-%d %H:%M") %>
            </div>


            <div class="image">
                <%= attachment_image_tag @topics, :image, format: 'jpeg', size: "400x300",  fallback: "no_image.jpg" %>
            </div>


            <div class="title ">
                <%= @topics.title %>
            </div>


            <div class="text ">
                <%= @topics.body %>
            </div>

        </div>


        <div class="row">
            <% if customer_signed_in? %>
                <% if @topics.favorited_by?(current_customer) %>
                    <%= link_to topic_favorites_path(@topics), method: :delete do %>
                        <%= @topics.favorites.count %>
                    <% end %>
                <% else %>
                    <%= link_to topic_favorites_path(@topics), method: :post do %>
                        <%= @topics.favorites.count %>
                    <% end %>
                <% end %>
            <% end %>
        </div>


        <div class= "title_comment">コメント</div>


        <table>
            <% @comments.each do |comment| %>
                <tr>

                    <td>
                        <%= comment.customer.name %>
                    </td>

                    <td>
                        <%= comment.comment %>
                    </td>

                    <td>
                        <% if customer_signed_in? && comment.customer == current_customer %>
                            <%= link_to "Destroy", topic_comment_path(comment), method: :delete %>
                        <% end %>
                    </td>

                </tr>
            <% end %>
        </table>


        <div class="row">
            <div class="page">

                <% if @topics.previous.present? %>
                    <%= link_to "PREV", topic_path(@topics.previous) %>
                <% end %>


                <%= link_to "LIST", topics_path %>


                <% if @topics.next.present? %>
                    <%= link_to "NEXT",topic_path(@topics.next) %>
                <% end %>

            </div>
        </div>


    </div>
</div>